### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by pschalk** [camunda/camunda-bpm-custom-batch#1]
release version: 1.0.0
next dev-version: 1.1.0-SNAPSHOT

Hi Christian,

can you please do a release build for the initial version of the extension?

Best regards,
Patrick

**Comment by hawky-4s-** [comment]
Hi @pschalk, I still have some test failures/errors running maven:

```
15:02:24 -------------------------------------------------------
15:02:24  T E S T S
15:02:24 -------------------------------------------------------
15:02:25 Running org.camunda.bpm.extension.batch.CustomBatchBuilderTest
15:02:25 SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
15:02:25 SLF4J: Defaulting to no-operation (NOP) logger implementation
15:02:25 SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
15:02:25 Apr 07, 2017 3:02:25 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
15:02:25 INFO: Loading XML bean definitions from class path resource [camunda.cfg.xml]
15:02:31 Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.861 sec
15:02:31 Running org.camunda.bpm.extension.batch.CustomBatchItTest
15:02:31 Apr 07, 2017 3:02:31 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
15:02:31 INFO: Loading XML bean definitions from class path resource [camundaITTest.cfg.xml]
15:02:37 Tests run: 2, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 6.442 sec <<< FAILURE!
15:02:37 jobIsInErrorStateAfterException(org.camunda.bpm.extension.batch.CustomBatchItTest)  Time elapsed: 5.127 sec  <<< FAILURE!
15:02:37 java.lang.AssertionError: 
15:02:37 Expecting actual not to be null
15:02:37 	at org.camunda.bpm.extension.batch.CustomBatchItTest.jobIsInErrorStateAfterException(CustomBatchItTest.java:62)
15:02:37 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:02:37 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:02:37 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:02:37 	at java.lang.reflect.Method.invoke(Method.java:498)
15:02:37 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
15:02:37 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
15:02:37 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
15:02:37 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
15:02:37 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
15:02:37 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
15:02:37 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
15:02:37 	at org.camunda.bpm.engine.test.ProcessEngineRule$1.evaluate(ProcessEngineRule.java:165)
15:02:37 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
15:02:37 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
15:02:37 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
15:02:37 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
15:02:37 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
15:02:37 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
15:02:37 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
15:02:37 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
15:02:37 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
15:02:37 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
15:02:37 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
15:02:37 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
15:02:37 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
15:02:37 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:02:37 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:02:37 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:02:37 	at java.lang.reflect.Method.invoke(Method.java:498)
15:02:37 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
15:02:37 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
15:02:37 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
15:02:37 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
15:02:37 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
15:02:37 
15:02:37 jobIsInErrorStateAfterException(org.camunda.bpm.extension.batch.CustomBatchItTest)  Time elapsed: 5.129 sec  <<< ERROR!
15:02:37 org.camunda.bpm.engine.OptimisticLockingException: ENGINE-03005 Execution of 'DELETE MessageEntity[502]' failed. Entity was updated by another transaction concurrently.
15:02:37 	at org.camunda.bpm.engine.impl.db.EnginePersistenceLogger.concurrentUpdateDbEntityException(EnginePersistenceLogger.java:125)
15:02:37 	at org.camunda.bpm.engine.impl.db.entitymanager.DbEntityManager.handleOptimisticLockingException(DbEntityManager.java:323)
15:02:37 	at org.camunda.bpm.engine.impl.db.entitymanager.DbEntityManager.flushDbOperationManager(DbEntityManager.java:295)
15:02:37 	at org.camunda.bpm.engine.impl.db.entitymanager.DbEntityManager.flush(DbEntityManager.java:278)
15:02:37 	at org.camunda.bpm.engine.impl.interceptor.CommandContext.flushSessions(CommandContext.java:247)
15:02:37 	at org.camunda.bpm.engine.impl.interceptor.CommandContext.close(CommandContext.java:176)
15:02:37 	at org.camunda.bpm.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:113)
15:02:37 	at org.camunda.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:66)
15:02:37 	at org.camunda.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
15:02:37 	at org.camunda.bpm.engine.impl.ManagementServiceImpl.deleteBatch(ManagementServiceImpl.java:467)
15:02:37 	at org.camunda.bpm.extension.batch.CustomBatchItTest.tearDown(CustomBatchItTest.java:45)
15:02:37 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:02:37 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:02:37 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:02:37 	at java.lang.reflect.Method.invoke(Method.java:498)
15:02:37 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
15:02:37 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
15:02:37 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
15:02:37 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
15:02:37 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
15:02:37 	at org.camunda.bpm.engine.test.ProcessEngineRule$1.evaluate(ProcessEngineRule.java:165)
15:02:37 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
15:02:37 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
15:02:37 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
15:02:37 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
15:02:37 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
15:02:37 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
15:02:37 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
15:02:37 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
15:02:37 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
15:02:37 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
15:02:37 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
15:02:37 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
15:02:37 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
15:02:37 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:02:37 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:02:37 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:02:37 	at java.lang.reflect.Method.invoke(Method.java:498)
15:02:37 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
15:02:37 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
15:02:37 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
15:02:37 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
15:02:37 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
15:02:37 
15:02:37 Running org.camunda.bpm.extension.batch.core.CustomBatchConfigurationHelperTest
15:02:37 Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 sec
15:02:37 
15:02:37 Results :
15:02:37 
15:02:37 Failed tests:   jobIsInErrorStateAfterException(org.camunda.bpm.extension.batch.CustomBatchItTest): (..)
15:02:37 
15:02:37 Tests in error: 
15:02:37   jobIsInErrorStateAfterException(org.camunda.bpm.extension.batch.CustomBatchItTest): ENGINE-03005 Execution of 'DELETE MessageEntity[502]' failed. Entity was updated by another transaction concurrently.
15:02:37 
15:02:37 Tests run: 8, Failures: 1, Errors: 1, Skipped: 0
```

Could you please have a look at it?

Cheers,
Christian

**Comment by pschalk** [comment]
Hi @hawky-4s- ,

this should already be fixed with the last commit.
(Is a timing issue ... )
I think there was no new Jenkins run since my last commit, right?

Regards,
Patrick

**Comment by pschalk** [comment]
Hi @hawky-4s- 

looks like the last problem on jenkins has nothing to do with the extension itself? 

`ERROR: Failed to deploy artifacts: Could not transfer artifact org.camunda.bpm.extension.batch:camunda-bpm-custom-batch-core:jar:1.0.0 from/to central (https://oss.sonatype.org/content/repositories/snapshots): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/org/camunda/bpm/extension/batch/camunda-bpm-custom-batch-core/1.0.0/camunda-bpm-custom-batch-core-1.0.0.jar. Return code is: 400, ReasonPhrase: Bad Request.`

Or is there some misconfiguration in the pom? 

Regards,
Patrick

**Comment by hawky-4s-** [comment]
Hi @pschalk,

I will try to check that today and come back to you afterwards.

Cheers,
Christian

**Comment by pschalk** [comment]
Hi @hawky-4s- ,

any news on this?

Regards,
Patrick

**Comment by hawky-4s-** [comment]
Hi @pschalk,

I had a look into the failing build issue. There are 2 things causing it to fail.

1. The version is already set to 1.0.0. Normally, the maven release would take care of that, when you ping/assign me the corresponding GitHub issue. There is no need to do anything there.

2. There are still the same test failures on our Jenkins, even with the latest fixes:

`
java.lang.AssertionError: 
Expecting actual not to be null
	at org.camunda.bpm.extension.batch.CustomBatchItTest.jobIsInErrorStateAfterException(CustomBatchItTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.camunda.bpm.engine.test.ProcessEngineRule$1.evaluate(ProcessEngineRule.java:165)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
`

**Comment by pschalk** [comment]
Hi @hawky-4s- ,

thanks for your fast reply.

1) O sorry, my fault, I thought I have to this. I've set it back to some minor version.

2) Hm strange ... I've now just ignored the test for the release, I'll think of some better way to test this. 

Please can you try it again? 

Regards,
Patrick

**Comment by pschalk** [comment]
Hi @hawky-4s- ,

I've seen that the Jenkins build is now stable, but up to now it's not deployed to central, right?

Regards,
Patrick

**Comment by hawky-4s-** [comment]
Hi @pschalk,

I did the release a few minutes ago. It should be available on Maven Central shortly.
Please close the issue, when you have checked the artifact availability on Maven Central: https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.camunda.bpm.extension.batch%22

Cheers,
Christian

PS: Sorry, that it took so long.

**Comment by pschalk** [comment]
Hi @hawky-4s- ,

Many thanks Christian, is on central :) 

Regards,
Patrick

PS: No Problem, was my fault. Failing tests, wrong project version, ...
